name: Ensure Clean Notebook Metadata

on:
  push:
    branches:
        - '**'
    paths:
        - '*.ipynb'
  pull_request:
    branches:
      - '**'
    paths:
      - '*.ipynb'

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Notebooks for clean metadata
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1